# Generated by Django 5.1.4 on 2026-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comparisonresult',
            new_name='api_compari_search__bb0ed1_idx',
            old_name='api_compari_search__585c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_normali_69545d_idx',
            old_name='api_product_normali_8c26de_idx',
        ),
        migrations.AddField(
            model_name='platform',
            name='brand_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
