# Generated by Django 5.1.4 on 2026-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_api_compari_search__585c5f_idx_api_compari_search__bb0ed1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIdentityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('raw_title', models.CharField(max_length=512)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('family', models.CharField(blank=True, max_length=120)),
                ('variant', models.CharField(blank=True, max_length=120)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('canonical_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
