# Generated by Django 5.1.4 on 2026-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productidentitycache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productidentitycache',
            old_name='quantity',
            new_name='size',
        ),
        migrations.AddField(
            model_name='productidentitycache',
            name='flavour',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
