# Generated by Django 5.1.4 on 2026-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_quantity_productidentitycache_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_a_name', models.CharField(db_index=True, max_length=255)),
                ('product_b_name', models.CharField(db_index=True, max_length=255)),
                ('comparable', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('same_brand', models.BooleanField(default=False)),
                ('same_variant', models.BooleanField(default=False)),
                ('same_quantity', models.BooleanField(default=False)),
                ('same_category', models.BooleanField(default=False)),
                ('preferred_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_a_name', 'product_b_name'], name='api_substit_product_c931e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('product_a_name', 'product_b_name'), name='unique_substitute_pair')],
            },
        ),
    ]
