# Generated by Django 5.1.4 on 2026-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_substitutecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValidationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_a_raw', models.CharField(db_index=True, max_length=255)),
                ('product_b_raw', models.CharField(db_index=True, max_length=255)),
                ('same_product', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_a_raw', 'product_b_raw'], name='api_product_product_bd2b7d_idx')],
                'constraints': [models.UniqueConstraint(fields=('product_a_raw', 'product_b_raw'), name='unique_validation_pair')],
            },
        ),
    ]
